@server = https://chrissho97-improved-succotash-9pg76w7qx6p27rp6-8080.preview.app.github.dev

###
GET {{server}}

###
GET {{server}}/instrumentos

###
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Piano"}

###

###
GET {{server}}/categorias
###

###
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Cordofonos"}

###
GET {{server}}/categorias/2/instrumentos

###
GET {{server}}/instrumentos?size=2&page=1&sort=categorias,desc



